import HpIcon from "@/components/hp-icon.vue";

const iconNames = [
  "alert-octagone",
  "calendar",
  "copy",
  "globe",
  "minus",
  "skills",
  "alert",
  "candidates",
  "credit-card-declined",
  "heart",
  "moon",
  "star",
  "archive",
  "check-circle",
  "credit-card",
  "help",
  "notallowed",
  "sun",
  "arrow-down",
  "check",
  "cross-circle",
  "house",
  "notifications",
  "trash",
  "arrow-left",
  "chevron-down",
  "cross",
  "image",
  "pencil",
  "unlocked",
  "arrow-right",
  "chevron-left",
  "diamond",
  "import",
  "placeholder",
  "upload",
  "arrow-top",
  "chevron-right",
  "discover",
  "layers",
  "play",
  "user",
  "at",
  "chevron.top",
  "drag",
  "lightning",
  "plug",
  "video",
  "attach",
  "chronometer",
  "expand",
  "plus-square",
  "wallet",
  "bag",
  "clean",
  "eye-closed",
  "location",
  "plus",
  "work-bag",
  "binoculars",
  "eye",
  "locked",
  "blocked",
  "file",
  "mail",
  "questions",
  "book",
  "cog",
  "folder",
  "micro",
  "score",
  "box",
  "computer",
  "gift",
  "minus-square",
  "search",
];

export default {
  title: "Components/Icon",
  component: HpIcon,
  argTypes: {},
};

const Template = (args) => ({
  components: { HpIcon },
  setup() {
    return { args, iconNames };
  },
  template: `<div style="display:flex">
    <div style="margin-right:8px">
        <hp-icon v-for="icon in iconNames" :name="icon" v-bind="args"> </hp-icon>
    </div>
  </div>`,
});

export const Primary = Template.bind({});
