name: Cypress Tests

on:
  push:
    branches:
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          build: npm run build
          start: npm run dev
          wait-on: "http://localhost:3000"
    env:
      # pass the Dashboard record key as an environment variable
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      # pass the project ID from the secrets through environment variable
      CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
